准备移除smartdns

diff --git a/.github/workflows/build-on-linux.yml b/.github/workflows/build-on-linux.yml
--- a/.github/workflows/build-on-linux.yml
+++ b/.github/workflows/build-on-linux.yml
@@ -180,35 +180,35 @@ jobs:
           echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
           docker tag docker.io/owt5008137/vbox:latest ghcr.io/${{ github.repository_owner }}/vbox:latest
           docker push ghcr.io/${{ github.repository_owner }}/vbox:latest
-  build_smartdns: # job id, can be any string
-    # Job name is Build And Publish
-    name: Build smartdns
-    # This job runs on Linux
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
-    env:
-      GOOS: linux
-      GOARCH: amd64
-      CGO_ENABLED: 0
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - uses: actions/setup-go@v5
-        with:
-          go-version: ">=1.21.0"
-      - name: Build smartdns
-        shell: bash
-        run: |
-          which docker || true;
-          mkdir smartdns
-          cd smartdns
-          curl -k -L --retry 10 --retry-max-time 1800 -o smartdns.Dockerfile https://raw.githubusercontent.com/owent-utils/docker-setup/main/setup-router/smartdns/smartdns.Dockerfile
-          curl -k -L --retry 10 --retry-max-time 1800 -o smartdns.origin.conf https://raw.githubusercontent.com/owent-utils/docker-setup/main/setup-router/smartdns/smartdns.origin.conf
-          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "owt5008137" --password-stdin docker.io
-          docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --force-rm --tag docker.io/owt5008137/smartdns:latest -f smartdns.Dockerfile .
-          docker push docker.io/owt5008137/smartdns:latest
+  # build_smartdns: # job id, can be any string
+  #   # Job name is Build And Publish
+  #   name: Build smartdns
+  #   # This job runs on Linux
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest]
+  #   runs-on: ${{ matrix.os }}
+  #   env:
+  #     GOOS: linux
+  #     GOARCH: amd64
+  #     CGO_ENABLED: 0
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - uses: actions/setup-go@v5
+  #       with:
+  #         go-version: ">=1.21.0"
+  #     - name: Build smartdns
+  #       shell: bash
+  #       run: |
+  #         which docker || true;
+  #         mkdir smartdns
+  #         cd smartdns
+  #         curl -k -L --retry 10 --retry-max-time 1800 -o smartdns.Dockerfile https://raw.githubusercontent.com/owent-utils/docker-setup/main/setup-router/smartdns/smartdns.Dockerfile
+  #         curl -k -L --retry 10 --retry-max-time 1800 -o smartdns.origin.conf https://raw.githubusercontent.com/owent-utils/docker-setup/main/setup-router/smartdns/smartdns.origin.conf
+  #         echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "owt5008137" --password-stdin docker.io
+  #         docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --force-rm --tag docker.io/owt5008137/smartdns:latest -f smartdns.Dockerfile .
+  #         docker push docker.io/owt5008137/smartdns:latest
   build_coredns_release: # job id, can be any string
     # Job name is Build And Publish
     name: Build coredns (release)
